jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }

    env:
      IMAGE_NAME_RAW: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normalize image name (lowercase)
        run: |
          echo "IMAGE_NAME=$(echo "${IMAGE_NAME_RAW}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "Using IMAGE_NAME=$IMAGE_NAME"

      - name: Show Dockerfile used (sanity)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          test -f ./Dockerfile || (echo "Dockerfile NOT found at ./Dockerfile"; exit 1)
          echo "----- Dockerfile head -----"
          sed -n '1,80p' ./Dockerfile
          echo "---------------------------"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (:latest)
        uses: docker/build-push-action@v6
        with:
          context: .              # CHANGE if your PHP lives in ./php
          file: ./Dockerfile      # CHANGE to ./php/Dockerfile if needed
          push: true
          no-cache: true          # avoids stale cached stages
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64
