name: Publish Docker image (latest)

on:
  push:
    branches: [ main ]   # build when main changes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # needed to push to GHCR

    env:
      IMAGE_NAME_RAW: ghcr.io/${{ github.repository }}  # e.g., ghcr.io/owner/repo

    steps:
      - uses: actions/checkout@v4

      # GHCR requires lowercase repo names
      - name: Normalize image name to lowercase
        run: |
          echo "IMAGE_NAME=$(echo "${IMAGE_NAME_RAW}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "Using IMAGE_NAME=${IMAGE_NAME_RAW} -> $(echo "${IMAGE_NAME_RAW}" | tr '[:upper:]' '[:lower:]')"

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push :latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile            # change if your Dockerfile is in a subfolder
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64        # add ,linux/arm64 if you need multi-arch
