name: Build and push Docker image

on:
  push:
    branches: [ "**" ]     # listen to ALL branches so you can test easily
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ toLower(github.repository) }}  # force lowercase

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show ref & files (diagnostics)
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "IMAGE_NAME=${IMAGE_NAME}"
          ls -la
          test -f Dockerfile && echo "Dockerfile found" || (echo "Dockerfile NOT found"; exit 1)

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile        # change if your Dockerfile lives elsewhere
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
