name: Build and push Docker image

on:
  push:
    branches: [ main ]     # only main
    tags: [ "v*" ]         # e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME_RAW: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - name: Normalize image name (lowercase)
        run: |
          echo "IMAGE_NAME=$(echo "${IMAGE_NAME_RAW}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "Using IMAGE_NAME=$IMAGE_NAME"

      - name: Sanity check
        run: |
          test -f Dockerfile || (echo "Dockerfile NOT found at ./Dockerfile" && exit 1)
          ls -la

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch       # :main
            type=ref,event=tag          # :v1.0.0
            type=sha                    # :sha-xxxx

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile           # change if your Dockerfile is elsewhere
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
